### ISSUE TITLE
Slide组件滑动感觉很卡，如何解决？

### ISSUE THREAD

**Issue by ONE-SUNDAY** [tgideas/motion#23]

**Comment by hahnzhu** [comment]
是因为你的页面结构太复杂，动效太多了？

**Comment by githubFree** [comment]
能提供一下实际的案例地址吗

**Comment by ONE-SUNDAY** [comment]
准确的说在Android机器上，我使用了两台机器分别是：Sony Z5和坚果 扫你们的demo，滑动起来会有卡顿感。

**Comment by cnwander** [comment]
感觉很卡，可能是多方面因素造成的，没有具体案例地址不好判断哦

**Comment by Rhain** [comment]
在安卓机器上Slide组件滑动确实感觉卡。动效比较多点，如果是动效引起的卡顿，需要怎么优化呢？ @cnwander  @hahnzhu

**Comment by hahnzhu** [comment]
@Rhain @ONE-SUNDAY 可以看看这篇文章：http://isux.tencent.com/nine-question-of-swipe-html5-page.html
