### ISSUE TITLE
silde 组件enable()方法bug

### ISSUE THREAD

**Issue by Rhain** [tgideas/motion#25]
默认情况下第一屏向下拉不会拉到最后一屏，但是当disable(0) 再enable(0)的时候，第一屏可以拉到最后一屏。

**Comment by cnwander** [comment]
disable(0, 'next');
enable(0, 'next');

**Comment by Rhain** [comment]
嗯，
disable(0, 'next');
enable(0, 'next'); 可以解决提到的问题。
